Issue 388
nanovms/ops pull request #737
Opened 2020-10-28 17:16 UTC by chaitanya-baraskar

Issue - #388 

Added progress bar for better user experience.
Created separate utils package to remove interdependency and refactored code accordingly.

2020-10-28 17:25 UTC, eyberg commented on cmd/image.go
> +	"github.com/briandowns/spinner"
i'm not opposed to using a new spinner but don't we have an existing one?

2020-10-28 17:28 UTC, eyberg commented on utils/utils.go
> +func ArrayToString(a []int, delim string) string {
govet will complain here

2020-10-28 18:33 UTC, eyberg requested changes
I don't care which one you pick but I think we are already using https://github.com/schollz/progressbar/ as a progressbar - i'd just do one or the other - no need for 2, everything else looks fine

2020-10-29 08:24 UTC, chaitanya-baraskar commented
@eyberg this is how spinner works https://asciinema.org/a/zANzbg2cnEieFGyVxnmAg2vAY

2020-10-29 16:41 UTC, eyberg commented
ok, well in that case maybe we should just use the existing progressbar - the whole point of that tkt was to provide an indicator of progress (25% done, 50% done, etc.) - there are facilities in the aws sdk to show progress for things like that

2020-10-29 17:03 UTC, chaitanya-baraskar commented
Ok. I am not aware of this feature from SDK let me do some research.

2020-10-31 16:03 UTC, closed without merging